
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

# stylesheets loaded in the <head>
stylesheets:
- /css/mestino.css

# scripts loaded in the end of the body
scripts:
- /js/mestino.js

background: https://api.dujin.org/bing/1920.php
#第一栏是组件,目前可选[info,music]
sidebar:
  info: 
    #可选qq,github,music,email,facebook,twitter,youtube,wechat。第二个参数为链接
    qq: qq
    github: https://github.com/wzy2006
    email: "mailto:3450354617@qq.com"
  music:

    
