
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

# stylesheets loaded in the <head>
stylesheets:
- /css/mestino.css

# scripts loaded in the end of the body
scripts:
- /js/mestino.js

background: https://img.xjh.me/random_img.php?type=bg&ctype=nature&return=302&random=<%- Math.random()%>

sidebar:
  info: 
    a: a
    
